sudo: required
services:
  - docker

before_install:
  - docker build -t alindumitru/deployableproject -f Dockerfile.dev .

script:
  - docker run alindumitru/deployableproject npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "deployableproject"
  env: "Docker-env"
  bucket_name: "elassticbeanstalk-us-west-2306567424"
  bucket_path: "deplotableproject"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"