sudo: required
services:
  - docker

before_install:
  - docker build -t alindumitru/deployableproject -f Dockerfile.dev .

script:
  - docker run alindumitru/deployableproject npm run test -- --coverage